# Generated by Django 4.0.6 on 2023-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_details_geometriclocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='building_details',
            name='Building_Number',
            field=models.IntegerField(null=True),
        ),
    ]
