# Generated by Django 4.0.6 on 2023-04-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_details_building_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building_details',
            old_name='Serial_NUmber',
            new_name='Serial_Number',
        ),
    ]
